### ISSUE TITLE
Inne i ett recept vore det bra om bildslidern inte är på 100vh. Så att man ser rubrik, metadata samt lite av description utan att behöva scrolla ner

### ISSUE THREAD

**Issue by MagnusEnstrom** [Papput/ameliabakar#29]
75% av höjden kanske är rimligt? Nu är den 100vh vilket gör att man möts bara av bilden när man klickar in på ett recept

**Comment by Papput** [comment]
Låter rimligt 😊

**Comment by Papput** [comment]
- [ ] Som en användare vill jag kunna se Rubrik, metadata & description utan att scrolla ner

**Comment by MagnusEnstrom** [comment]
![image](https://user-images.githubusercontent.com/93531980/151555422-013cc908-ef9e-4316-bc57-ead4d0b1ff51.png)

**Comment by MagnusEnstrom** [comment]
typ sådär, svårt att förklara :D som bilden till höger är det just nu, vore bättre om den är mer som den till vänster. Någon rimlig siffra på slidern vet jag inte men 75% höjd blir kanske bra?
